#[derive(Clone, Copy, PartialEq, Eq)]
pub enum AssetCategory {
    Icon,
    Font,
}

pub struct LibraryAsset {
    pub name: &'static str,
    pub bytes: &'static [u8],
    pub category: AssetCategory,
}

pub struct Template {
    pub name: &'static str,
    pub description: &'static str,
    pub json_content: &'static str,
    pub required_prefixes: &'static [&'static str],
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum FontSource {
    Internal, // Found in base IWAD (e.g. STCFN)
    Package,  // Built into Cacoco's library
}

pub struct FontDefinition {
    pub name: &'static str,
    pub description: &'static str,
    pub stem: &'static str,
    pub is_hud: bool,
    pub source: FontSource,
}

macro_rules! a {
    ($name:literal, $cat:expr) => {
        LibraryAsset {
            name: $name,
            bytes: include_bytes!(concat!("../assets/library/", $name)),
            category: $cat,
        }
    };
}

pub const ASSETS: &[LibraryAsset] = &[
    a!("ammo_ov1.png", AssetCategory::Icon),
    a!("ammo_ov2.png", AssetCategory::Icon),
    a!("ammo_ov3.png", AssetCategory::Icon),
    a!("arm_god.png", AssetCategory::Icon),
    a!("arm_high.png", AssetCategory::Icon),
    a!("arm_low.png", AssetCategory::Icon),
    a!("bmtyarm.png", AssetCategory::Icon),
    a!("bmtygod1.png", AssetCategory::Icon),
    a!("bmtygod2.png", AssetCategory::Icon),
    a!("bmtyhel1.png", AssetCategory::Icon),
    a!("bmtyhel2.png", AssetCategory::Icon),
    a!("boom2sls.png", AssetCategory::Icon),
    a!("boom4sls.png", AssetCategory::Icon),
    a!("boom6sls.png", AssetCategory::Icon),
    a!("boomity.png", AssetCategory::Icon),
    a!("dsda_wpn.png", AssetCategory::Icon),
    a!("progbar1.png", AssetCategory::Icon),
    a!("progbar2.png", AssetCategory::Icon),
    a!("progbar3.png", AssetCategory::Icon),
    a!("progbar4.png", AssetCategory::Icon),
    a!("progbar5.png", AssetCategory::Icon),
    a!("progbar6.png", AssetCategory::Icon),
    a!("progbar7.png", AssetCategory::Icon),
    a!("stkeys6.png", AssetCategory::Icon),
    a!("stkeys7.png", AssetCategory::Icon),
    a!("stkeys8.png", AssetCategory::Icon),
    a!("tag_amm.png", AssetCategory::Icon),
    a!("tag_ammo.png", AssetCategory::Icon),
    a!("tag_arm.png", AssetCategory::Icon),
    a!("tag_arm1.png", AssetCategory::Icon),
    a!("tag_arm2.png", AssetCategory::Icon),
    a!("tag_arms.png", AssetCategory::Icon),
    a!("tag_frag.png", AssetCategory::Icon),
    a!("tag_god.png", AssetCategory::Icon),
    a!("tag_heal.png", AssetCategory::Icon),
    a!("tag_hel.png", AssetCategory::Icon),
    a!("tag_inf1.png", AssetCategory::Icon),
    a!("tag_inf4.png", AssetCategory::Icon),
    a!("tag_key.png", AssetCategory::Icon),
    a!("tag_max2.png", AssetCategory::Icon),
    a!("tag_max3.png", AssetCategory::Icon),
    a!("tag_max4.png", AssetCategory::Icon),
    a!("tag_max6.png", AssetCategory::Icon),
    a!("tag_sts.png", AssetCategory::Icon),
    a!("tag_wea.png", AssetCategory::Icon),
    a!("tag_wpn.png", AssetCategory::Icon),

    a!("prbmarm1.png", AssetCategory::Icon),
    a!("prbmarm2.png", AssetCategory::Icon),
    a!("prbmarm3.png", AssetCategory::Icon),
    a!("prbmhel1.png", AssetCategory::Icon),
    a!("prbmhel2.png", AssetCategory::Icon),
    a!("prbmhel3.png", AssetCategory::Icon),
    a!("prbmhel4.png", AssetCategory::Icon),

    a!("dgt2num0.png", AssetCategory::Font),
    a!("dgt2num1.png", AssetCategory::Font),
    a!("dgt2num2.png", AssetCategory::Font),
    a!("dgt2num3.png", AssetCategory::Font),
    a!("dgt2num4.png", AssetCategory::Font),
    a!("dgt2num5.png", AssetCategory::Font),
    a!("dgt2num6.png", AssetCategory::Font),
    a!("dgt2num7.png", AssetCategory::Font),
    a!("dgt2num8.png", AssetCategory::Font),
    a!("dgt2num9.png", AssetCategory::Font),
    a!("dgt2prcn.png", AssetCategory::Font),

    a!("dgt3num0.png", AssetCategory::Font),
    a!("dgt3num1.png", AssetCategory::Font),
    a!("dgt3num2.png", AssetCategory::Font),
    a!("dgt3num3.png", AssetCategory::Font),
    a!("dgt3num4.png", AssetCategory::Font),
    a!("dgt3num5.png", AssetCategory::Font),
    a!("dgt3num6.png", AssetCategory::Font),
    a!("dgt3num7.png", AssetCategory::Font),
    a!("dgt3num8.png", AssetCategory::Font),
    a!("dgt3num9.png", AssetCategory::Font),
    a!("dgt3prcn.png", AssetCategory::Font),

    a!("dgt4num0.png", AssetCategory::Font),
    a!("dgt4num1.png", AssetCategory::Font),
    a!("dgt4num2.png", AssetCategory::Font),
    a!("dgt4num3.png", AssetCategory::Font),
    a!("dgt4num4.png", AssetCategory::Font),
    a!("dgt4num5.png", AssetCategory::Font),
    a!("dgt4num6.png", AssetCategory::Font),
    a!("dgt4num7.png", AssetCategory::Font),
    a!("dgt4num8.png", AssetCategory::Font),
    a!("dgt4num9.png", AssetCategory::Font),
    a!("dgt4prcn.png", AssetCategory::Font),

    a!("dgt5num0.png", AssetCategory::Font),
    a!("dgt5num1.png", AssetCategory::Font),
    a!("dgt5num2.png", AssetCategory::Font),
    a!("dgt5num3.png", AssetCategory::Font),
    a!("dgt5num4.png", AssetCategory::Font),
    a!("dgt5num5.png", AssetCategory::Font),
    a!("dgt5num6.png", AssetCategory::Font),
    a!("dgt5num7.png", AssetCategory::Font),
    a!("dgt5num8.png", AssetCategory::Font),
    a!("dgt5num9.png", AssetCategory::Font),
    a!("dgt5prcn.png", AssetCategory::Font),

    a!("dgt6coln.png", AssetCategory::Font),
    a!("dgt6num0.png", AssetCategory::Font),
    a!("dgt6num1.png", AssetCategory::Font),
    a!("dgt6num2.png", AssetCategory::Font),
    a!("dgt6num3.png", AssetCategory::Font),
    a!("dgt6num4.png", AssetCategory::Font),
    a!("dgt6num5.png", AssetCategory::Font),
    a!("dgt6num6.png", AssetCategory::Font),
    a!("dgt6num7.png", AssetCategory::Font),
    a!("dgt6num8.png", AssetCategory::Font),
    a!("dgt6num9.png", AssetCategory::Font),
    a!("dgt6prcn.png", AssetCategory::Font),

    a!("dgt7num0.png", AssetCategory::Font),
    a!("dgt7num1.png", AssetCategory::Font),
    a!("dgt7num2.png", AssetCategory::Font),
    a!("dgt7num3.png", AssetCategory::Font),
    a!("dgt7num4.png", AssetCategory::Font),
    a!("dgt7num5.png", AssetCategory::Font),
    a!("dgt7num6.png", AssetCategory::Font),
    a!("dgt7num7.png", AssetCategory::Font),
    a!("dgt7num8.png", AssetCategory::Font),
    a!("dgt7num9.png", AssetCategory::Font),

    a!("dig033.png", AssetCategory::Font),
    a!("dig037.png", AssetCategory::Font),
    a!("dig043.png", AssetCategory::Font),
    a!("dig045.png", AssetCategory::Font),
    a!("dig046.png", AssetCategory::Font),
    a!("dig047.png", AssetCategory::Font),
    a!("dig048.png", AssetCategory::Font),
    a!("dig049.png", AssetCategory::Font),
    a!("dig050.png", AssetCategory::Font),
    a!("dig051.png", AssetCategory::Font),

    a!("etl1num0.png", AssetCategory::Font),
    a!("etl1num1.png", AssetCategory::Font),
    a!("etl1num2.png", AssetCategory::Font),
    a!("etl1num3.png", AssetCategory::Font),
    a!("etl1num4.png", AssetCategory::Font),
    a!("etl1num5.png", AssetCategory::Font),
    a!("etl1num6.png", AssetCategory::Font),
    a!("etl1num7.png", AssetCategory::Font),
    a!("etl1num8.png", AssetCategory::Font),
    a!("etl1num9.png", AssetCategory::Font),

    a!("etl3num0.png", AssetCategory::Font),
    a!("etl3num1.png", AssetCategory::Font),
    a!("etl3num2.png", AssetCategory::Font),
    a!("etl3num3.png", AssetCategory::Font),
    a!("etl3num4.png", AssetCategory::Font),
    a!("etl3num5.png", AssetCategory::Font),
    a!("etl3num6.png", AssetCategory::Font),
    a!("etl3num7.png", AssetCategory::Font),
    a!("etl3num8.png", AssetCategory::Font),
    a!("etl3num9.png", AssetCategory::Font),

    a!("etl4num0.png", AssetCategory::Font),
    a!("etl4num1.png", AssetCategory::Font),
    a!("etl4num2.png", AssetCategory::Font),
    a!("etl4num3.png", AssetCategory::Font),
    a!("etl4num4.png", AssetCategory::Font),
    a!("etl4num5.png", AssetCategory::Font),
    a!("etl4num6.png", AssetCategory::Font),
    a!("etl4num7.png", AssetCategory::Font),
    a!("etl4num8.png", AssetCategory::Font),
    a!("etl4num9.png", AssetCategory::Font),

    a!("etl5num0.png", AssetCategory::Font),
    a!("etl5num1.png", AssetCategory::Font),
    a!("etl5num2.png", AssetCategory::Font),
    a!("etl5num3.png", AssetCategory::Font),
    a!("etl5num4.png", AssetCategory::Font),
    a!("etl5num5.png", AssetCategory::Font),
    a!("etl5num6.png", AssetCategory::Font),
    a!("etl5num7.png", AssetCategory::Font),
    a!("etl5num8.png", AssetCategory::Font),
    a!("etl5num9.png", AssetCategory::Font),

    a!("etm1prcn.png", AssetCategory::Font),
    a!("etm2prcn.png", AssetCategory::Font),
    a!("etm3num0.png", AssetCategory::Font),
    a!("etm3num1.png", AssetCategory::Font),
    a!("etm3num2.png", AssetCategory::Font),
    a!("etm3num3.png", AssetCategory::Font),
    a!("etm3num4.png", AssetCategory::Font),
    a!("etm3num5.png", AssetCategory::Font),
    a!("etm3num6.png", AssetCategory::Font),
    a!("etm3num7.png", AssetCategory::Font),
    a!("etm3num8.png", AssetCategory::Font),
    a!("etm3num9.png", AssetCategory::Font),
    a!("etm3prcn.png", AssetCategory::Font),
    a!("etm6num0.png", AssetCategory::Font),
    a!("etm6num1.png", AssetCategory::Font),
    a!("etm6num2.png", AssetCategory::Font),
    a!("etm6num3.png", AssetCategory::Font),
    a!("etm6num4.png", AssetCategory::Font),
    a!("etm6num5.png", AssetCategory::Font),
    a!("etm6num6.png", AssetCategory::Font),
    a!("etm6num7.png", AssetCategory::Font),
    a!("etm6num8.png", AssetCategory::Font),
    a!("etm6num9.png", AssetCategory::Font),
    a!("etm6prcn.png", AssetCategory::Font),
    a!("etm7prcn.png", AssetCategory::Font),

    a!("etr2slsh.png", AssetCategory::Font),
    a!("etr3slsh.png", AssetCategory::Font),
    a!("etr6slsh.png", AssetCategory::Font),
    a!("etrdivd2.png", AssetCategory::Font),
    a!("etrdivdr.png", AssetCategory::Font),
    a!("etrinf1.png", AssetCategory::Font),
    a!("etrinf3.png", AssetCategory::Font),

    a!("ets2num0.png", AssetCategory::Font),
    a!("ets2num1.png", AssetCategory::Font),
    a!("ets2num2.png", AssetCategory::Font),
    a!("ets2num3.png", AssetCategory::Font),
    a!("ets2num4.png", AssetCategory::Font),
    a!("ets2num5.png", AssetCategory::Font),
    a!("ets2num6.png", AssetCategory::Font),
    a!("ets2num7.png", AssetCategory::Font),
    a!("ets2num8.png", AssetCategory::Font),
    a!("ets2num9.png", AssetCategory::Font),
    a!("ets3num0.png", AssetCategory::Font),
    a!("ets3num1.png", AssetCategory::Font),
    a!("ets3num2.png", AssetCategory::Font),
    a!("ets3num3.png", AssetCategory::Font),
    a!("ets3num4.png", AssetCategory::Font),
    a!("ets3num5.png", AssetCategory::Font),
    a!("ets3num6.png", AssetCategory::Font),
    a!("ets3num7.png", AssetCategory::Font),
    a!("ets3num8.png", AssetCategory::Font),
    a!("ets3num9.png", AssetCategory::Font),
    a!("ets6num0.png", AssetCategory::Font),
    a!("ets6num1.png", AssetCategory::Font),
    a!("ets6num2.png", AssetCategory::Font),
    a!("ets6num3.png", AssetCategory::Font),
    a!("ets6num4.png", AssetCategory::Font),
    a!("ets6num5.png", AssetCategory::Font),
    a!("ets6num6.png", AssetCategory::Font),
    a!("ets6num7.png", AssetCategory::Font),
    a!("ets6num8.png", AssetCategory::Font),
    a!("ets6num9.png", AssetCategory::Font),
    a!("ets7num9.png", AssetCategory::Font),

    a!("fragnum0.png", AssetCategory::Font),
    a!("fragnum1.png", AssetCategory::Font),
    a!("fragnum2.png", AssetCategory::Font),
    a!("fragnum3.png", AssetCategory::Font),
    a!("fragnum4.png", AssetCategory::Font),
    a!("fragnum5.png", AssetCategory::Font),
    a!("fragnum6.png", AssetCategory::Font),
    a!("fragnum7.png", AssetCategory::Font),
    a!("fragnum8.png", AssetCategory::Font),
    a!("fragnum9.png", AssetCategory::Font),

    a!("prbm033.png", AssetCategory::Font),
    a!("prbm037.png", AssetCategory::Font),
    a!("prbm043.png", AssetCategory::Font),
    a!("prbm045.png", AssetCategory::Font),
    a!("prbm046.png", AssetCategory::Font),
    a!("prbm047.png", AssetCategory::Font),
    a!("prbm048.png", AssetCategory::Font),
    a!("prbm049.png", AssetCategory::Font),
    a!("prbm050.png", AssetCategory::Font),
    a!("prbm051.png", AssetCategory::Font),
    a!("prbm052.png", AssetCategory::Font),
    a!("prbm053.png", AssetCategory::Font),
    a!("prbm054.png", AssetCategory::Font),
    a!("prbm055.png", AssetCategory::Font),
    a!("prbm056.png", AssetCategory::Font),
    a!("prbm057.png", AssetCategory::Font),
    a!("prbm058.png", AssetCategory::Font),
    a!("prbm065.png", AssetCategory::Font),
    a!("prbm066.png", AssetCategory::Font),
    a!("prbm067.png", AssetCategory::Font),
    a!("prbm068.png", AssetCategory::Font),
    a!("prbm069.png", AssetCategory::Font),
    a!("prbm070.png", AssetCategory::Font),
    a!("prbm071.png", AssetCategory::Font),
    a!("prbm072.png", AssetCategory::Font),
    a!("prbm073.png", AssetCategory::Font),
    a!("prbm074.png", AssetCategory::Font),
    a!("prbm075.png", AssetCategory::Font),
    a!("prbm076.png", AssetCategory::Font),
    a!("prbm077.png", AssetCategory::Font),
    a!("prbm078.png", AssetCategory::Font),
    a!("prbm079.png", AssetCategory::Font),
    a!("prbm080.png", AssetCategory::Font),
    a!("prbm081.png", AssetCategory::Font),
    a!("prbm082.png", AssetCategory::Font),
    a!("prbm083.png", AssetCategory::Font),
    a!("prbm084.png", AssetCategory::Font),
    a!("prbm085.png", AssetCategory::Font),
    a!("prbm086.png", AssetCategory::Font),
    a!("prbm087.png", AssetCategory::Font),
    a!("prbm088.png", AssetCategory::Font),
    a!("prbm089.png", AssetCategory::Font),
    a!("prbm090.png", AssetCategory::Font),
    a!("prbm091.png", AssetCategory::Font),
    a!("prbm093.png", AssetCategory::Font),
];

pub const CLASSIC_PREFIXES: &[&str] = &[];
pub const NIGHTKICKER_PREFIXES: &[&str] = &[
    "ammo_ov", "arm_", "bmty", "boom", "dsda", "progbar", "tag_", "prbm",
    "dgt", "dig", "etl", "etm", "etr", "ets", "frag",
];

pub const TEMPLATES: &[Template] = &[
    Template {
        name: "Classic Vanilla",
        description: "The original STARMS and STBAR, a great starting point for any new HUD.",
        json_content: include_str!("../assets/templates/classicSTBAR.json"),
        required_prefixes: CLASSIC_PREFIXES,
    },
    Template {
        name: "Nightkicker",
        description: "A compact, modern Statusbar showcasing the power of SBARDEF with dynamic elements.",
        json_content: include_str!("../assets/templates/nightkicker.json"),
        required_prefixes: NIGHTKICKER_PREFIXES,
    },
];

pub const FONTS: &[FontDefinition] = &[
    FontDefinition {
        name: "Classic HUD",
        description: "You got the shotgun!",
        stem: "STCFN",
        is_hud: true,
        source: FontSource::Internal,
    },
    FontDefinition {
        name: "Classic Status Bar",
        description: "100% Health. 200% Armor.",
        stem: "STT",
        is_hud: false,
        source: FontSource::Internal,
    },
    FontDefinition {
        name: "Classic Gray",
        description: "For when you're missing 3456 or 7.",
        stem: "STG",
        is_hud: false,
        source: FontSource::Internal,
    },
    FontDefinition {
        name: "Classic Yellow",
        description: "For all that ammunition you have.",
        stem: "STYS",
        is_hud: false,
        source: FontSource::Internal,
    },
    FontDefinition {
        name: "Classic Intermission",
        description: "100% Kills. 9% Items. 20% Secrets.",
        stem: "WI",
        is_hud: false,
        source: FontSource::Internal,
    },
    FontDefinition {
        name: "Automap (Orange)",
        description: "Modern style, kinda sweet.",
        stem: "dgt2",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Automap (Yellow)",
        description: "Modern style, a little sour.",
        stem: "dgt3",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Automap (Green)",
        description: "Modern style, a bit bitter.",
        stem: "dgt4",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Automap (Blue)",
        description: "Modern style, quite refreshing.",
        stem: "dgt5",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Automap (White)",
        description: "Modern style, great on a hot day.",
        stem: "dgt6",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Automap (Grey)",
        description: "Modern style, but hard to read.",
        stem: "dgt7",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity (Red)",
        description: "Eternity style, kinda health-poi.",
        stem: "etl1",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity (Gold)",
        description: "Eternity style, feels like IDDQD.",
        stem: "etl3",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity (Green)",
        description: "For serviceable armor.",
        stem: "etl4",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity (Blue)",
        description: "Eternity style, for dying 50% less.",
        stem: "etl5",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity Ammo (Gold)",
        description: "A chunky font for premium bullets.",
        stem: "etm3",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity Ammo (White)",
        description: "A chunky font for economic bullets.",
        stem: "etm6",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity Weapons (Orange)",
        description: "Thin and Great for active weapons.",
        stem: "ets2",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity Weapons (Yellow)",
        description: "For the weapons in your bag.",
        stem: "ets3",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "Eternity Weapons (White)",
        description: "...We also have it in white.",
        stem: "ets6",
        is_hud: false,
        source: FontSource::Package,
    },
    FontDefinition {
        name: "PRBoom+ HUD",
        description: "A simple and modern HUD font.",
        stem: "prbm",
        is_hud: true,
        source: FontSource::Package,
    },
];